@baseUrl = http://127.0.0.1:8080
@studentId = 1
@spaceId = 1
@pathId = 1
@nodeId = 1
@quizId = 1

###########################################################
# 1. STUDENT DASHBOARD BEFORE JOIN
###########################################################

### Dashboard
GET {{baseUrl}}/api/students/{{studentId}}/dashboard
Accept: application/json


###########################################################
# 2. JOIN LEARNING SPACE BY INVITE CODE
###########################################################

### Join class
POST {{baseUrl}}/api/students/{{studentId}}/learning-spaces/join
Content-Type: application/json

{
  "inviteCode": "JAVA_BASIC_01"
}


###########################################################
# 3. DASHBOARD AFTER JOIN
###########################################################

### Dashboard after joining class
GET {{baseUrl}}/api/students/{{studentId}}/dashboard
Accept: application/json


###########################################################
# 4. VIEW ROADMAP
###########################################################

### Roadmap list
GET {{baseUrl}}/api/learning-spaces/{{spaceId}}/learning-paths
Accept: application/json


###########################################################
# 5. VIEW NODE + DOCUMENT
###########################################################

### Node list
GET {{baseUrl}}/api/learning-paths/{{pathId}}/nodes
Accept: application/json

### Document list
GET {{baseUrl}}/api/learning-paths/{{pathId}}/documents
Accept: application/json


###########################################################
# 6. VIEW QUIZ
###########################################################

### Quiz list
GET {{baseUrl}}/api/learning-nodes/{{nodeId}}/quizzes
Accept: application/json

### Quiz detail
GET {{baseUrl}}/api/quizzes/{{quizId}}
Accept: application/json