spring.application.name=FlippedClass

<<<<<<< HEAD

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FlippedClassDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sa@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
=======
# Database Configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FlippedClassDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


flippedclass.app.jwtSecret=======================FlippedClassProjectSecretKeyByAntigravity=========================
flippedclass.app.jwtExpirationMs=86400000

# Google OAuth2 Client ID
flippedclass.app.googleClientId=790885197434-tj8p3el3prc6n6fakj3udbuoqml6dpq1.apps.googleusercontent.com

# Mật khẩu khởi tạo ban đầu cho tài khoản Superuser
flippedclass.app.initialPassword=MatKhauGiangVien123

# ==========================================
# SWAGGER & OPENAPI CONFIGURATION

# 1. Thay đổi đường dẫn mở Swagger UI ngắn gọn (http://localhost:8080/swagger)
springdoc.swagger-ui.path=/swagger

# 2. Thay đổi đường dẫn tải file JSON định nghĩa API (http://localhost:8080/api-docs)
springdoc.api-docs.path=/api-docs

# 3. Sắp xếp danh sách API theo chữ cái A-Z
springdoc.swagger-ui.operationsSorter=alpha

# 4. Quản lý Bật/Tắt Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ==========================================
# SPRING MAIL CONFIGURATION (SMTP GMAIL)

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Điền email Gmail của bạn dưới đây
spring.mail.username=flippedclass2026@gmail.com
# Điền Mật khẩu ứng dụng 16 ký tự Google cấp vào đây (viết liền không dấu cách)
spring.mail.password=Flippedclass2026@@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> origin/Nguyenhuy
