spring.application.name=FC_FlatForm

# Database Configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FC_FlatForm;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

flippedclass.app.jwtSecret=======================FlippedClassProjectSecretKeyByAntigravity=========================
flippedclass.app.jwtExpirationMs=86400000 
# Google OAuth2 Client ID
flippedclass.app.googleClientId=790885197434-tj8p3el3prc6n6fakj3udbuoqml6dpq1.apps.googleusercontent.com

flippedclass.app.initialPassword=MatKhauGiangVien123

#  URL backend (FE dùng fullUrl để phát video)
flippedclass.app.baseUrl=http://localhost:8080

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.operationsSorter=alpha
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.basedir=.tomcat
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

# Force UTF-8 Encoding for Spring Boot & Thymeleaf
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8


